### ISSUE TITLE
Cloned from kmanjari/hrms

### ISSUE THREAD

**Issue by khanof89** [glowlogix/gleamhrm#30]
You have cloned this code from https://GitHub.com/kmanjari/hrms and then labelled it as yours, no one has any problem of you extending it and improving it, but instead of deleting all the references of original author you could have just forked it.

**Comment by musamamasood** [comment]
Hi @khanof89, 

Please provide reference with codebases so we can investigate further.

**Comment by khanof89** [comment]
I am not going into matching files and show you proofs of the clone, but I know and you know that it is not your original work. Undoubtedly you have made improvements in the project but its wrong using someones work without credits.

**Comment by musamamasood** [comment]
I'm not one who only worked on it, so If you claim something then please provide proof. 

Further, You can email proof to **masood at glowlogix.com** and we are happy to accomodate accordingly.
